# Generated by Django 3.1.2 on 2020-12-22 07:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement_3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_3')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_3')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 12, 22, 7, 18, 8, 905940, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_2')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_2')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 12, 22, 7, 18, 8, 905940, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_1')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_1')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 12, 22, 7, 18, 8, 904920, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SideChallenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='side_challenge')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='side_challenge')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 12, 22, 7, 18, 8, 905940, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
