# Generated by Django 3.1.2 on 2021-01-23 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement_4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_4')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_4')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 36, 26, 849030, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement_3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_3')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_3')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 36, 26, 848179, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_2')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_2')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 36, 26, 847383, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='challenge_statement_1')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='challenge_statement_1')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 36, 26, 846472, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SideChallenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='side_challenge')),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('raw', models.FileField(upload_to='side_challenge')),
                ('raw_url', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 36, 26, 849961, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register1', models.BooleanField(default=False)),
                ('submit1', models.BooleanField(default=False)),
                ('register2', models.BooleanField(default=False)),
                ('submit2', models.BooleanField(default=False)),
                ('register3', models.BooleanField(default=False)),
                ('submit3', models.BooleanField(default=False)),
                ('register4', models.BooleanField(default=False)),
                ('submit4', models.BooleanField(default=False)),
                ('registerSide', models.BooleanField(default=False)),
                ('submitSide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
