# Generated by Django 3.1.2 on 2020-12-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201215_2055'),
        ('users', '0002_auto_20201217_1155'),
    ]

    operations = [
    ]
